### PR TITLE
WIP: feature: python generator

### PR DESCRIPTION
**Pull request by austin362667**
https://www.loom.com/share/b027dad7cca34c619eeb1dabae91d519

### CODE REVIEW

**Comment by austin362667** [comment]
@ccckmit 
> fn mean(...) 和 mean:=fn(...) 兩者都可以寫
> 前者只能放在 stmt 層次，而 lambda 則是放在 item 層次

然而：

Python 裡的 lambda function 只接受 expressions，並不允許 statements
FYR: [python3 docs](https://docs.python.org/3/reference/expressions.html#lambda)

所以範例測資 array.s1 是不允許這樣寫的（？）
```
mean :=fn(a) {
    s:=0.0
    for x in a s = s+x
    return s/a.length
}
```

**Comment by austin362667** [comment]
parse lambda/function
```
  if (nid){
      b1 = block();
  } else {
      skip('{');
      skip('?');
      b1 = expr();
      skip('}');
  }
```

gen python lambda/functiom
```
  if (id){
      emit("def ");
      gen_code(id);
      gen_code(params);
      emit(":");
      gen_code(block);
  } else {
      emit("lambda ");
      gen_list(params->list->head, ",");
      emit(":");
      gen_code(block);
  }
```

**Review by ccckmit — COMMENTED** [review]
gen0.c 中拿掉了

>      emit(" // (%d) \n", i); \

然後加上

>      emit(" # (%d) \n", i); \

這樣 js 不就不能跑了 ... ?

我想是否用 `#ifdef __PYTHON__` 來處理

```
#define line(i) \
  if (show_line) { \
    if (i>0) { \
      int len = 50-(int)(ep-ebuf); \
      emit("%*s", max(len, 0), ""); \
#ifdef __PYTHON__
      emit(" # (%d) \n", i); \
#else
      emit(" // (%d) \n", i); \
#endif
    } \
    else { emit("\n"); }; ep = ebuf; \
  }
```

然後在 gen_py.c 當中定義 `__PYTHON__`

**Comment by austin362667** [comment]
Both `javascript` and `dart` can choose either **block syntax** or **single expression syntax** for lambda function.

Since lambda function in `Python` only accepts expression syntax.

By subset of all three.
We may choose expression syntax over statement syntax to parse lambdas in s1 parser. It's fine.

e.g.,

- JS `elements.map( element => element.value )`
- Dart `elements.map( (element) => element.value )`
- Python `elements.map( lambda element: element.value )`

**Comment by ccckmit** [comment]
> Both `javascript` and `dart` can choose either **block syntax** or **single expression syntax** for lambda function.
> 
> Since lambda function in `Python` only accepts expression syntax.
> 
> By subset of all three. We may choose expression syntax over statement syntax to parse lambdas in s1 parser. It's fine.
> 
> e.g.,
> 
> * JS `elements.map( element => element.value )`
> * Dart `elements.map( (element) => element.value )`
> * Python `elements.map( lambda element: element.value )`

Good Idea ! I will try it.

**Pull request merged**
